// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeJZt7YH-lIEz7B7FwqvGX-wASncb5X3g',
    appId: '1:698147461557:web:22e31e6a303ebb45a761fc',
    messagingSenderId: '698147461557',
    projectId: 'todooapp-944d3',
    authDomain: 'todooapp-944d3.firebaseapp.com',
    storageBucket: 'todooapp-944d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6kfBa_RyZd_MFtu0HB6M3ku1b1yaXOxw',
    appId: '1:698147461557:android:80b5ee9ef923e97aa761fc',
    messagingSenderId: '698147461557',
    projectId: 'todooapp-944d3',
    storageBucket: 'todooapp-944d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjMseOGjFhxXTRnKALBn_0HbkzjB32gDQ',
    appId: '1:698147461557:ios:5934917ad79680c7a761fc',
    messagingSenderId: '698147461557',
    projectId: 'todooapp-944d3',
    storageBucket: 'todooapp-944d3.appspot.com',
    iosBundleId: 'com.example.todooapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjMseOGjFhxXTRnKALBn_0HbkzjB32gDQ',
    appId: '1:698147461557:ios:5934917ad79680c7a761fc',
    messagingSenderId: '698147461557',
    projectId: 'todooapp-944d3',
    storageBucket: 'todooapp-944d3.appspot.com',
    iosBundleId: 'com.example.todooapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeJZt7YH-lIEz7B7FwqvGX-wASncb5X3g',
    appId: '1:698147461557:web:f3dea6c398af9d63a761fc',
    messagingSenderId: '698147461557',
    projectId: 'todooapp-944d3',
    authDomain: 'todooapp-944d3.firebaseapp.com',
    storageBucket: 'todooapp-944d3.appspot.com',
  );
}
